import "./globals.css";
import { Inter } from "next/font/google";
import { ContextProvider } from "@/contexts/ContextProvider";
import Footer from "./components/Footer";
import Template from "./temlate";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Template>{children}</Template>
        </ContextProvider>
      </body>
    </html>
  );
}
